version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/usr/share/nginx/html
    ports:
      - '5173:80'
    depends_on:
      - client
      
  server:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - dbMongo
      - dbPostgres

  client:
    build: ./client
    ports:
      - '8080:80'
    volumes:
      - ./client:/app
      - /app/node_modules

  dbMongo:
    image: mongo:4.4.18
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'

  dbPostgres:
    image: postgres:13-alpine
    env_file:
      - server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - server/.env
    ports:
      - "5050:80"
    depends_on:
      dbPostgres:
        condition: service_healthy

volumes:
  mongodb_data:
  postgres_data:
  node_modules: